#+TITLE: Rust Primer
#+SUBTITLE: Handy rust stuff I keep forgetting
#+AUTHOR: Njagi Mwaniki
#+OPTIONS: date:nil


* Packaging
** New project
Cargo

#+BEGIN_SRC bash
rustc <files>         # compile files
cargo build           # compile project
cargo build --release # compile with optimizations
cargo run             # compile and run
cargo check           # Checks that code compiles but doesn't produce and executable
cargo new             # generate project
cargo doc --open      # build documentation provided by all of your dependencies locally and open it in your browser
#+END_SRC

Executable

#+BEGIN_SRC bash
cargo new ...
#+END_SRC

Library

#+BEGIN_SRC bash
cargo new ...
#+END_SRC

** Dependencies

** cargo.toml

* Syntax
** Closures
Fn taking a lambda

#+BEGIN_SRC rust
pub fn affine_wavefronts_align<T>(
    affine_wavefronts: AffineWavefronts,
    match_lambda: T,
    traceback_lambda: T,
    pattern_length: i32,
    text_length: i32 ) where T: Fn(i32, i32) -> bool {}
#+END_SRC 

** Range

exclusive
#+BEGIN_SRC rust
<start>..<end>
#+END_SRC 

inclusive
#+BEGIN_SRC rust
<start>..=<end>
#+END_SRC 

** Loops
loop
#+BEGIN_SRC rust
loop {
  /*
    The break statement can be used to exit a loop at anytime,
    whereas the continue statement can be used to skip the rest 
    of the iteration and start a new one.
   */
}
#+END_SRC 

for
#+BEGIN_SRC rust
for i in 0..max {
  
}
#+END_SRC 

** Iterators
With side effects use `for_each`

#+BEGIN_SRC rust
let my_str: &[u8] = "ACTGA".as_bytes();
my_str.iter().for_each(|a| println!("{}", a));
#+END_SRC 

Without side effects go with `map`
#+BEGIN_SRC rust
let my_str: &[u8] = "ACTGA".as_bytes();
let char_vec: Vec<u8> = my_str.iter().map(|a| a+2).collect::<Vec<u8>>();
#+END_SRC

** Strings & chars
`u8` to `char`
#+BEGIN_SRC rust
<u8> as char
#+END_SRC 

** Variables
#+BEGIN_SRC rust
let <name>: type = <value>;
#+END_SRC

** Types

** Array
#+BEGIN_SRC rust
let <var_name>: [<type_of_content>; <size>] = <value>;
#+END_SRC
Initialize 100 value array with 0 repeated 100 times

#+BEGIN_SRC rust
let mut tally_array: [usize; 100] = [0; 100];
#+END_SRC

** Vector
initialize a vector of given number of values use vec! macro
#+BEGIN_SRC rust
vec![0; len]
#+END_SRC


Construct a new, empty Vec<T> with the specified capacity.
#+BEGIN_SRC rust
let mut vec = Vec::with_capacity(10);
#+END_SRC

** Imports
#+BEGIN_SRC rust
use <import>;
#+END_SRC

** Comments
Single line
#+BEGIN_SRC rust
//
#+END_SRC

Multi line
#+BEGIN_SRC rust
/*

*/
#+END_SRC

* Tests
** Running tests

Running a specific ignored test and have it print stuff

#+BEGIN_SRC bash
cargo test <test_name> -- --ignored --nocapture  
#+END_SRC

Running a regular test with $nocapture$

#+BEGIN_SRC bash
cargo test test_run_length_encode -- --nocapture
#+END_SRC

Running a specific test

#+BEGIN_SRC bash
cargo test <test_name>
#+END_SRC

** Writing tests

Just tests

#+BEGIN_SRC rust
#[cfg(test)]
mod tests {
    
    use super::*;

    #[test]
    fn test_run_length_encode() {
        assert_eq!(2 + 2, 4);
    }
}
#+END_SRC

Ignoring tests

#+BEGIN_SRC rust
#[cfg(test)]
mod tests {
    #[test]
    fn test_run_length_encode() {
        assert_eq!(2 + 2, 4);
    }

    // Ignore tests
    #[ignore]
    #[test]
    fn test_run_length_encode() {
        assert_eq!(2 + 2, 4);
    }
}
#+END_SRC
* Error handling

Switching from an ~expect~ call to a ~match~ expression is how you generally
move from crashing on an error to handling the error.

#+BEGIN_SRC rust
  // // declare string var
  let mut guess = String::new();

  // read user input from stdin
  io::stdin().read_line(&mut guess).expect("Failed to read line");

  // convert the user input to u32
  let guess: u32 = match guess.trim().parse() {
                Ok(k) => k,
                Err(_) => {
                    println!("Please enter a number");
                    continue;
                },
            };
#+END_SRC

* Terms
Associated function: A function implemented on a type
Some languages call it a static method.
e.g ~String::new();~ is implemented on the ~String~ type. 

Result is an error handling type enum
It's cariants are
Ok(<val>)
Err

Methods of the result type include: ~expect~,
