* Part 2: The Turn-Key Revolution: A New View of Business
** Chapter 7: The turn key revolution
*** Turning the key: The business format franchise
**** Trade name franchise
The franchiser licenses the right to small companies to market its nationally
 known products locally
***** Belief
Selling the name alone is enough

**** Business Format Franchise
Not only lend the name to the smaller franchise but also an entire system of
 doing things.
***** Belief
 Lies in the belief that the true product of a business is not what it sells
 but how it sells it.
 The true product of the business is the business itself.

*** Selling the business instead of the product
Creating a systems dependent not a people dependent business.

Working /on/ the business vs working /in/ the business.
Work on how to mass produce the business.

** Chapter 8: The franchise prototype
** Chapter 11: Your business development program
Your business development process is the step by step guide through which 
you convert your existing business into a perfectly organized model for
 thousands more just like it.

It's composed of:
  1. Your primary aim
  2. Your strategic objective
  3. Your organizational strategy
  4. Your management strategy
  5. Your people strategy
  6. Your marketing strategy
  7. Your systems strategy

** Chapter 12: Your primary aim
What do I value most?
What kind of life do I want?
What do I want my life to look like, to feel like?
Who do I wish to be

What kind of life do I want to have lived?
Begin living your life as if it were important

Living intentionally

Your primary aim is the vision necessary to bring your business to life
and your life to your business.

** Chapter 13: Your strategic objective
Your business strategy and plan should be reduced to a set of simple and clearly
stated standards.

It's a tool for measuring your progress towards a specific end.

**** The first standard: money
Gross revenue. 
  - How big is your vision?
  - How big will your company be once its done?

Gross profits
Pre-tax and after-tax profits

How much money do I need to be independent of work? To be free?

If your aim is to sell it how much do you want for it?
  - x10 earnings?
  - x20 earnings

When do you want it?
  - 10 years from now?
  - 5 years?

Why would anyone buy it?
  - Because it works!
  - You built it so that it would work better than anyone else's
  - You invented a turn key solution to your specific kind of business problems
  - An absolutely predictable business that does what it promises to do every single time
  - Because it can give you anything you want it can give your prospective buyer anything they want

**** The second standard: an opportunity worth pursing
A business that can fulfill the financial standards you've created &
for your primary aim and your strategic objective.

Does this business alleviate a frustration experienced by a large enough
group of consumers to make it worth my while?

***** What kind of business am I in?
The commodity is what your customer feels as he walks out of your business.
What the customer feels about your business, not the commodity?

People don't buy commodities, they buy feelings.

***** Who is my customer?
Define them:
 - age
 - income
 - sex
 - family status
 - education
 - profession etc

**** Standards three through
 - When is your prototype going to be completed?
 - Where are you going to be in business?
 - How are you going to be in business?
 - What standards will you insist upon?
   * cleanliness
   * management
   * hiring and firing
   * training etc

The standards you create will shape both your business and the experience you have of your business.

Document the things you know how to do.


** Chapter 14: Your organizational strategy
Get a fucking org chart

*** Organizing around personalities
Most companies organize around personalities rather than around functions.
Around people rather than around accountabilities or responsibilities.
The result is almost always chaos.

If everybody's doing everything then who's accountable for anything?

*** Organizing your company
Think of the business as a corporation and instead of thinking of each 
other as partners think of each other as shareholders.


Outside of the business you are *shareholders*.
Inside the business you are *employees*.

Describes the org chart

**** Write a position contract
It is *not* a job description. It's a contract.

A summary of the results to be achieved by each position in the company
The work the occupant of that position is accountable for
A list of standards by which the results are to be evaluated
A line for the signature of the one who agrees to fulfill this.


It provides a sense of commitment and accountability

Describes who's to stand up and what they're being counted on to produce.

What's needed for the top role is organization, thoroughness and
conscientiousness.

**** Prototyping the Position: Replacing Yourself with a System
You now focus on where you'd start working *in* the business.
As employees, not as partners COO etc.
Doing tactical not strategic work.

  - Tactical work is what technicians do.
  - Strategic work is what their managers do.

Coming up with an operations manual (for orchestration) after 
innovation and quantification.

Sales operations manual
Script for handling:
  - incoming calls
  - outgoing calls
  - meeting the customer at the door etc

Figure it out and advertise for someone with the willingness to learn and an open mind.


He shows them the org chart and where they'd lie in it.
He talks to them to determine who among them has a vision that coincides with theirs.

 > Won't I seem like a mad man?

At the moment of hiring you move up the org chart and start to manage 
the system not the person.
A logic is established. An integrated whole.
Create an org chart for how the org will look x years from now 
rather than how it is now.
Create a very detailed description of each position and sign the 
position contracts for each one.

You are each of those employees until you replace yourself with someone that is.
You must be able to differentiate amongst the roles
 - discriminate between what's most important and what's least important

Make it so that (to the best of your knowledge) your business must work.

Once you've done that you've got to follow the rules because if you 
can't nobody else will.
You're the owner.

You must then walk your talk.

** Chapter 15: Your management strategy
You can't afford great people, what you need is a management system.
The means through which your franchise prototype 
produces the results that you want.

The system will be your management strategy.
The means through which your franchise prototype produces 
the results you want.

The system will help __ the unpredictability of your people.

*** What is a management system?
Management development - the process through which you create your
management system.

The purpose is not just to create an efficient prototype but an effective one.

Find out about a user once and store it.

 - Consistency is everything

*Hear* out your customer every single time.

Orchestrate a solution

Just have a series of checklists
Color code it.

Each task and the order in which it should be completed
This lets you train almost instantly and have them produce a consistent result.

It's about the little things.

** Chapter 16: Your people strategy
Won't people get tired of the checklist?
You can't get people to do what you want.
Appeal to their desire.

Create an environment in which doing it is more
important to your people than not doing it.
Doing it well will therefore become a way of life.

*** Take your people seriously
Take your people seriously. Not like kids.
Consider your people to be *important*.

You have to take your operation seriously.
It's more than just an x business.
It should be an expression of who you are and what you believe in.
It's all about that mutual respect.

*** The work
/The work we do is a reflection of who we are./
The job is inside yourself.

Work is an opportunity to see yourself as who you really are.

Make sure people understand the idea behind the work they're being asked to do.

Some values: 
  1. The customer is not always right but whether he is or not your work is to
     make him feel that he is right.
  2. Everyone is expected to work towards the best they can be at the task
     they're accountable for
     When they can't do it:
     - act like they are until they get around to it
     - leave
  3. The place where everything we know how to do is tested by what we don't 
     know how to do. The conflict between the two creates growth.

Look for players in your game. For people who want more than just a job.

People want not just an exciting place to work but a place with a clearly
defined structure; a game.

The degree to which people do what you ask represents how much they buy into
your idea.
Your people strategy is how you communicate the game.

It should be more than a place where people just go to work.

It must be about *how* you act.
You have to believe it.

*** The rules of the game
 1. Never figure out what your people want to do then create a game out of it.
    The game exists in nature. You're discovering it.
 2. Never create a game you're unwilling to play yourself.
    They'll find out and never let you forget about it
 3. Make sure there are ways of winning the game without ending it.
    The game never ends but give them little victories.
 4. Change the game from time to time - the tactics not the strategy.
 5. Never expect the game to be self sustaining. People must be reminded of it
    constantly.
    One on ones.
    The game only exists in as far as people believe it does.
 6. The game has to make sense.
 7. The game needs to be fun from time to time
 8. If you can't think of a good game, steal one

*** The logic of the game
Let work have purpose.
What's missing is /a game worth playing/.
A place that replaces the home most of us have lost.
Give people a transcendent meaning.

  - integrity
  - intention
  - commitment
  - vision
  - excellence

*** Playing the game
The medium of communicating the game is as important as the idea.
Through manuals, by example.

The hiring process is the first and most important medium for communicating 
your idea.

Codify the hiring process.
Apologize to those who don't make it through.

The system is indeed the solution
 
You need people who want to play your game, not people who believe that they
have a better one.

**** The hierarchy of systems
*it* is the purpose of your business.
 1. How we do it here
 2. How we recruit hire and train
 3. How we manage it here
 4. How we change it here

It's the system, not the people that will differentiate your business from all
others.

** Chapter 17: Your marketing strategy
It starts, lives and dies with your customer.
Forget about *your* dreams, vision, interests etc forget about everything but
your customer.

What the customer wants is probably significantly different from what they think
they want.

*** The irrational decision maker
it's your customer's unconscious mind where all the action is.

People make the decision then look for justifications to support it.
Buying decisions are made irrationally.

*** The two pillars of a successful marketing strategy
You can't know what the customer wants because they don't know either.

If you can know *who* your customer is you can tell *why* they buy.
Learn the demographics and psychographics of your client.

You can then start to construct a prototype to satisfy their unconscious needs.
Scientifically rather than arbitrarily

 - What demographic?
 - Which colors to use?
 - What words?

How to answer that is by asking them.
Give them a reward for them telling you.

| Large company names | Small business names |
|---------------------+----------------------|
| lead generation     | marketing            |
| lead conversion     | sales                |
| client fulfillment  | operations           |
|                     |                      |


The system should be well integrated

Getting them to come back for more is the primary aim of every business.
A customer you have is a lot less expensive to sell to than one you don't have.

Where hierarchy (management system) and process (business development process)
meet

** Chapter 18: Your systems strategy
*** What is a system?
A set of things, actions, ideas and information that interact with each other,
and in so doing alter other systems.

A system should free you to do the things you want to do.

*** Three kinds of systems
There are 3 kinds of systems:
  1. Hard systems
Inanimate
  2. Soft systems
Animate or ideas
  3. Information systems
Provide info about the interaction between the two

**** Hard systems
The sign on the walls, the uniforms, no breaking UIs etc

**** Soft systems
To get Price's law use a system
A selling system is a soft system.
A selling system is a fully orchestrated interaction between you and your
customer.

***** The power point selling system
1. Identify the specific benchmarks--or customer decision points--in your
   selling process.
2. Literal *scripting* of the words that will get you to each one successfully.
3. Create various materials to be used with each script
4. memorization of each benchmark script
5. delivery of each script by your salespeople in identical fashion
6. Leave your people to communicate more effectively and improve upon it


Has two parts:
  - structure :: what you do
  - substance :: how you do it

****** structure
  1. The appointment presentation.
     Making the appointment
  2. The needs analysis presentation.
     a) re establish emotional commitment
     b) how you would like to proceed to fulfill your promise
  3. establish credibility in your prospect's mind by communicating
       a) your expertise in such matters
       b) your willingness to do what it takes to utilize your expertise on
         their behalf
  4. Describe the system and why it works so well. 
     Plus the impact it will have on the user.

**** Information systems
It would answer:

| Benchmark | Information                                          | value |
|-----------+------------------------------------------------------+-------|
|        1. | How many calls made                                  |       |
|        2. | How many prospects reached                           |       |
|        3. | How many appointments scheduled                      |       |
|        4. | How many appointments confirmed                      |       |
|        5. | How many appointment were held                       |       |
|        6. | How many needs analysis presentations were scheduled |       |
|        7. | How many needs analysis were confirmed               |       |
|        8. | How many needs analysis were completed               |       |
|        9. | How many presentation solutions scheduled?           |       |
|       10. | How many presentation solutions confirmed            |       |
|       11. | How many presentation solutions completed            |       |
|       12. | How many solutions sold?                             |       |
|       13. | What was the average dollar value?                   |       |


information -> systems strategy -> franchise prototype
** Chapter 19: A letter to Sarah
Talk about existentialism and all
